In [2]:
#1. 创建numpy数据

import numpy as np
#1.1一元函数，对一个数组操作
arr= np.arange(10)-10
#np.abs()
print('arr abs:\n',np.abs(arr))
#np.sqrt()
print('arr sqrt:\n',np.sqrt(arr+10))#平方根
#np.square()
print('arr square:\n',np.square(arr))#平方
#np.exp()
print('arr exp:\n',np.exp(arr+10)) #不能对负数取对数
#np.log
print('arr log:\n',np.log(np.exp(arr+10))) #log对应的底是e，log10对应的底是10
#np.sign():
print('arr sign:\n',np.sign(arr+5)) #计算正负号
#np.ceil()
print('arr ceil:\n',np.ceil(arr+0.3)) #大于等于改值的最小整数
#np.floor()
print('arr floor:\n',np.floor(arr+0.3))
#np.rint() 
print('arr rint:\n',np.rint(arr+0.3)) #四舍五入取整
#np.modf()
print('arr modf:\n',np.modf(arr+0.3)) #小数和整数分为两个部分返回

arr abs:
 [10  9  8  7  6  5  4  3  2  1]
arr sqrt:
 [0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
arr square:
 [100  81  64  49  36  25  16   9   4   1]
arr exp:
 [1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]
arr log:
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
arr sign:
 [-1 -1 -1 -1 -1  0  1  1  1  1]
arr ceil:
 [-9. -8. -7. -6. -5. -4. -3. -2. -1. -0.]
arr floor:
 [-10.  -9.  -8.  -7.  -6.  -5.  -4.  -3.  -2.  -1.]
arr rint:
 [-10.  -9.  -8.  -7.  -6.  -5.  -4.  -3.  -2.  -1.]
arr modf:
 (array([-0.7, -0.7, -0.7, -0.7, -0.7, -0.7, -0.7, -0.7, -0.7, -0.7]), array([-9., -8., -7., -6., -5., -4., -3., -2., -1., -0.]))


In [4]:
#无限大
#布尔值不能有无限大，要转化为浮点值，astype()
arr= np.arange(10)-10
arr_float = arr.astype(np.float)
arr_float[[0,2,4]]=np.NaN
arr_float[-1] = np.Inf
print('arr with Nan:\n',arr_float)
#np.isnan
print('arr nan:\n',np.isnan(arr_float))#判断是否为nan
#np.isinf()
print('arr inf:\n',np.isinf(arr_float)) #判断是否为无穷大

arr with Nan:
 [nan -9. nan -7. nan -5. -4. -3. -2. inf]
arr nan:
 [ True False  True False  True False False False False False]
arr inf:
 [False False False False False False False False False  True]


In [5]:
#2.二元函数，对两个数组作用
#创建两个随机数组
x=np.random.randn(10)
y=np.random.randn(10)
print('x:\n',x)
print('y:\n',y)
#np.add()
print('add:\n',np.add(x,y))
#np.subtract()
print('subtract:\n',np.subtract(x,y))
#np.multiply()
print('multiply:\n',np.multiply(x,y))
#np.divide()
print('divide:\n',np.divide(x,y))
#np.power() #避免无法计算要对x取绝对值
print('power:\n',np.power(np.abs(x),y))
#np.maxium()
#np.min()
#np.mod()求模
#np.copysign() 
#np.greater()
#np.less()\
#np.logical_and()

x:
 [ 1.50015362  0.90021466 -0.12833181  0.14419175 -0.83006986 -0.01640401
 -1.64170973  0.53972162  0.93631607  1.52368145]
y:
 [ 0.30950288 -0.81041699  1.71267891  0.91978662 -1.1629078  -0.65013984
  0.0291564  -0.42276933  1.29266881 -0.79277399]
add:
 [ 1.8096565   0.08979766  1.5843471   1.06397837 -1.99297767 -0.66654385
 -1.61255333  0.1169523   2.22898488  0.73090746]
subtract:
 [ 1.19065075  1.71063165 -1.84101072 -0.77559487  0.33283794  0.63373583
 -1.67086613  0.96249095 -0.35635274  2.31645544]
multiply:
 [ 0.46430186 -0.72954925 -0.21979119  0.13262564  0.96529472  0.0106649
 -0.04786635 -0.22817775  1.21034658 -1.20793502]
divide:
 [ 4.84697796e+00 -1.11080427e+00 -7.49304574e-02  1.56766525e-01
  7.13788196e-01  2.52315119e-02 -5.63070043e+01 -1.27663383e+00
  7.24327889e-01 -1.92196197e+00]
power:
 [ 1.13374273  1.08892687  0.02970729  0.16842426  1.24183018 14.4721177
  1.01455891  1.29786758  0.91845679  0.71615372]


In [ ]:
#3. 统计
data_arr = np.random.randn(20)
print('data_arr:\n',data_arr)
#data.sum()
#data.mean()
#data.std()
#data.var()
#data.max()
#data.min()
#data.argmin()
#data.argmax()
#data.cumsum()
#data.cumprod()

In [ ]:
#4.集合

In [ ]:
#5. 随机函数