In [3]:
import numpy as np

In [4]:
np.random.rand(5)

array([0.34542702, 0.31044364, 0.7728412 , 0.59869162, 0.06100628])

In [5]:
np.random.rand(5,5)

array([[0.77755042, 0.08667843, 0.38729218, 0.52335076, 0.80384279],
       [0.43305143, 0.91328496, 0.72980447, 0.92376219, 0.34125062],
       [0.74801073, 0.57314135, 0.49824949, 0.89313426, 0.14237581],
       [0.6837231 , 0.77301612, 0.31035742, 0.93221528, 0.38957112],
       [0.3283974 , 0.73934659, 0.19286684, 0.44410007, 0.16485604]])

In [8]:
np.random.randn(2)

array([-0.64732286,  0.45795095])

In [9]:
np.random.randn(4,4)

array([[ 0.17876363,  2.07292098, -1.21569659, -0.6662971 ],
       [-1.98605475,  0.57369296, -0.49195781, -1.61756069],
       [ 1.34339726,  1.25030151,  0.35797247, -1.10026696],
       [-0.64167373, -0.54994546,  1.14009559,  0.24152018]])

In [10]:
np.random.randint(1,100)  #只会返回一个值，randint就是随机选取一个数

30

In [11]:
np.random.randint(1,100,10)

array([40, 73, 57, 37, 34, 53, 43, 74, 31, 82])

In [15]:
arr=np.arange(25)

In [17]:
#reshape the array 
arr.reshape(5,5)  #但是一定要保证总数是一样的，然后形状可以随便变啊

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [18]:
arr.reshape(25,1)  #这是个二维列表吗？

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [19]:
arr.max()

24

In [20]:
arr.min()

0

In [ ]:
#返回最大值和最小值的index

In [21]:
arr.argmax()

24

In [ ]:
arr.argmin()

In [22]:
arr.dtype

dtype('int64')

In [ ]:
#**************************************numpy indexing**********************************

In [23]:
arr=np.arange(0,11)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
#注意开区间是不包括开头的
arr[5:]   #比如这里是指index>5后面的数字，但是不包括index=5

array([ 5,  6,  7,  8,  9, 10])

In [27]:
#不是开区间的就包括啊
arr[1:5]

array([1, 2, 3, 4])

In [28]:
#改变numpy中的数值
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [29]:
#r如果要改变所有的数值呢？就将所有的都选中，然后赋值啊
arr[:]=99
arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [ ]:
#~~~~~~~~~~~~~~~~~~~~~2d array indexing ~~~~~~~~~~~~~~~~~~~~

In [30]:
arr_2d = np.array([[2,3,4],[3,5,6],[5,4,3]])
arr_2d

array([[2, 3, 4],
       [3, 5, 6],
       [5, 4, 3]])

In [31]:
arr_2d[0]  #取第一行  ，所以在2维列表中的元素（列表）其实是一行，不是一列

array([2, 3, 4])

In [32]:
arr_2d[1][1]

5

In [ ]:
'''之前看了如何数数的一个方法，感觉也可以用在matrix 的indexing中，这就是位置方法，
第一个[1]表示按照行走一步（向下走一步），第二个[1]表示按照列走一步(向右走一步).
对于三维列表也可以这样理解。但是到了四维就没有办法了，没有办法想象四维空间
'''

In [33]:
arr_2d[1,2]  #这种方法也是可以的

6

In [34]:
arr_2d[:2,1:]  

array([[3, 4],
       [5, 6]])

In [35]:
arr_2d[:2] #取第0行和第1行，后面取列可以看作是取出行之后，然后对行进行操作

array([[2, 3, 4],
       [3, 5, 6]])

In [ ]:
#~~~~~~~~~~~~~~~~~~~~~~~~~conditional indexing and selection~~~~~~~~~~~~~~~~~~~~~~~

In [45]:
arr=np.arange(1,11)

In [46]:
bool_arr=arr > 5   #因为这个是判断条件，所以返回的一定是bool值

In [47]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [48]:
#use the boolean array to index and select the array
arr[bool_arr]  #这是为什么呢？

array([ 6,  7,  8,  9, 10])

In [49]:
#你想bool_arr是什么？其实是arr>5，所以就相当于
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [ ]:
#~~~~~~~~~~~~~~~~~~~~~~~~~2d array for  conditional indexing and selection~~~~~~~~~~~~~~~~~~~~~~~

In [50]:
arr_2d =np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [51]:
arr_2d[1:3] #包头不包尾

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [52]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [ ]:
#**************************************numpy operations**********************************

In [54]:
arr=np.arange(0,11)

In [55]:
#~~~~~~~~~~array with array function~~~~~~~~~~~~``

In [56]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
#~~~~~~~~~~array with scalar function~~~~~~~~~~~~

In [ ]:
#scalar means a single number 

In [57]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [58]:
arr*100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [ ]:
#~~~~~~~~~~universal functions~~~~~~~~~~~~

In [59]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [60]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [61]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [64]:
dir(np.array)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__self__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__text_signature__']