In [1]:
#1.对两个numpy 数组进行操作
import numpy as np
#集合的运用

#创建两个数组
nums_1=np.array([1,0,0,3,2,5])
nums_2=np.array([4,9,0,3,2,6])
print('nums_1:\n',nums_1)
print('nums_2:\n',nums_2)

nums_1:
 [1 0 0 3 2 5]
nums_2:
 [4 9 0 3 2 6]


In [4]:
import numpy as np
#集合的运用

#创建两个数组
nums_1=np.array([1,0,0,3,2,5])
nums_2=np.array([4,9,0,3,2,6])
print('nums_1:\n',nums_1)
print('nums_2:\n',nums_2)
#unique(x) 返回集合中唯一有序结果，即去重
print('unique:\n',np.unique(nums_1))
#intersect1d(x,y) 返回公共元素
print ('intersect1d:\n',np.intersect1d(nums_1,nums_2))
#union1d()并集
print('union1d:\n',np.union1d(nums_1,nums_2))
#setdiff1d() 差集 x不在y中的值，
print('setdiff1d',np.setdiff1d(nums_1,nums_2))
#setxor1d() 对称差，存在一个数组，但不同时存在两个数组，并集-交集
print('setxor1d',np.setxor1d(nums_1,nums_2))
#以上功能都可以自动排序

nums_1:
 [1 0 0 3 2 5]
nums_2:
 [4 9 0 3 2 6]
unique:
 [0 1 2 3 5]
intersect1d:
 [0 2 3]
union1d:
 [0 1 2 3 4 5 6 9]
setdiff1d [1 5]
setxor1d [1 4 5 6 9]


In [12]:
#随机函数
#可以返回各种各样的随机数，比如正态分布，均匀分布样本等
#seed
i=0
while (i<5):
    np.random.seed(3)
    print(np.random.seed(3))
    i+=1
#permutation
some_values = np.random.permutation(10)
print('some_values:\n',some_values)
#shuffle 打乱随机数
np.random.shuffle(some_values)
print('some_values:\n',some_values)
#rand
print('rand:\n',np.random.rand(10)) #生成从0到10比较均匀的随机数
#randint 
print('randint:\n',np.random.randint(-10,10,10))#范围-10到10
#randn
print('randn:\n',np.random.randn(10))
#binomial
print('binomial:\n',np.random.binomial(1,0.5,size=10)) #0.5为概率
#normal mean=5 std=2
print('normal:\n',np.random.normal(5,2,size=10))
#beta
print('beta:\n',np.random.beta(1,5,10))
#chisquare
print('chisquare:\n',np.random.chisquare(2,4))
#gamma
print('gamma:\n',np.random.gamma(2,2,10))
#uniform
print('uniform:\n',np.random.uniform(size=10))

None
None
None
None
None
some_values:
 [5 4 1 2 9 6 7 0 3 8]
some_values:
 [2 3 1 4 8 9 5 7 0 6]
rand:
 [0.21557701 0.35390507 0.49263593 0.91330145 0.76582638 0.97364827
 0.40236064 0.55277195 0.30636063 0.58661997]
randint:
 [ -3   1  -9   5   6  -5   7   4 -10 -10]
randn:
 [-0.40791451  1.24757841 -1.82938368 -1.59651767  0.69031204  0.92812246
  1.58653631  0.40130586 -1.26968864  0.46920629]
binomial:
 [1 1 1 1 0 0 1 0 1 1]
normal:
 [ 0.89134621  3.38531819 -0.79153191  7.18460929  3.82133143  6.9783684
  4.92382847  7.44536462  7.57231254  5.31644056]
beta:
 [0.16293661 0.10844018 0.12340904 0.05841294 0.04212414 0.01330594
 0.06633114 0.56242412 0.3747826  0.23094881]
chisquare:
 [0.66649552 4.27259023 1.57659824 3.52077879]
gamma:
 [1.82002322 1.94953292 2.99994825 0.90937998 1.28577165 1.47931679
 0.46024753 6.0748955  1.48943635 1.55116247]
uniform:
 [0.89773703 0.83524631 0.14631622 0.99544318 0.35572909 0.54713075
 0.49181555 0.12965838 0.86005346 0.2183979 ]


In [4]:
import numpy as np
np.__annotations__

AttributeError: module 'numpy' has no attribute '__annotations__'

In [8]:
dir(np.random)

['Lock',
 'RandomState',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'absolute_import',
 'beta',
 'binomial',
 'bytes',
 'chisquare',
 'choice',
 'dirichlet',
 'division',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'np',
 'operator',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'print_function',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_state',
 'shuffle',
 'standard_cauchy',
 'standard_exponential',
 'standard_gamma',
 'standard_normal',
 'standard_t',
 'test',
 'triangular',
 'uniform',
 'vonmises',
 'wald',
 'warnings',
 'weibull',
 'zipf']

In [9]:
dir(np.random.randint)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__self__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__text_signature__']

In [10]:
np.random.randint.__getattribute__

<method-wrapper '__getattribute__' of builtin_function_or_method object at 0x7f847acbbf30>

In [12]:
np.random.randint.__text_signature__

In [13]:
np.random.randint.__doc__

'\n        randint(low, high=None, size=None, dtype=\'l\')\n\n        Return random integers from `low` (inclusive) to `high` (exclusive).\n\n        Return random integers from the "discrete uniform" distribution of\n        the specified dtype in the "half-open" interval [`low`, `high`). If\n        `high` is None (the default), then results are from [0, `low`).\n\n        Parameters\n        ----------\n        low : int\n            Lowest (signed) integer to be drawn from the distribution (unless\n            ``high=None``, in which case this parameter is one above the\n            *highest* such integer).\n        high : int, optional\n            If provided, one above the largest (signed) integer to be drawn\n            from the distribution (see above for behavior if ``high=None``).\n        size : int or tuple of ints, optional\n            Output shape.  If the given shape is, e.g., ``(m, n, k)``, then\n            ``m * n * k`` samples are drawn.  Default is None, in which

In [15]:
dir(np.random.binomial)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__self__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__text_signature__']

In [16]:
np.random.binomial.__call__

<method-wrapper '__call__' of builtin_function_or_method object at 0x7f847acbc7e0>

In [20]:
np.random.binomial.__qualname__

'RandomState.binomial'

In [21]:
np.random.binomial.__self__

In [22]:
np.random.binomial.__getattribute__

<method-wrapper '__getattribute__' of builtin_function_or_method object at 0x7f847acbc7e0>

In [23]:
help(np.random.binomial)

Help on built-in function binomial:

binomial(...) method of mtrand.RandomState instance
    binomial(n, p, size=None)
    
    Draw samples from a binomial distribution.
    
    Samples are drawn from a binomial distribution with specified
    parameters, n trials and p probability of success where
    n an integer >= 0 and p is in the interval [0,1]. (n may be
    input as a float, but it is truncated to an integer in use)
    
    Parameters
    ----------
    n : int or array_like of ints
        Parameter of the distribution, >= 0. Floats are also accepted,
        but they will be truncated to integers.
    p : float or array_like of floats
        Parameter of the distribution, >= 0 and <=1.
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  If size is ``None`` (default),
        a single value is returned if ``n`` and ``p`` are both scalars.
        Otherwise, ``np.broadcas