In [ ]:
#1. 切片
#就和list一样操作

In [2]:
import numpy as np
#如果直接对np数据进行切片会直接改变原来的数据
origin_arr = np.arange(10)
print(origin_arr)
arr_slice = origin_arr[5:]
print(arr_slice)
arr_slice[-1] = 1024  
print(origin_arr)
print(arr_slice)
#这里虽然只修改了arr_slice的最后一个数据，但是原始数据origin_arr也被修改了

[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]
[   0    1    2    3    4    5    6    7    8 1024]
[   5    6    7    8 1024]


In [3]:
#需要用到在复制的是加上一个copy 
origin_arr = np.arange(10)
print(origin_arr)
arr_slice = origin_arr[5:].copy() #这说明切片数据是复制了的，而不是对原来的数据进行操作
print(arr_slice)
arr_slice[-1] = 1024  
print(origin_arr)
print(arr_slice)


[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[   5    6    7    8 1024]


In [4]:
#2. 二维数组的索引和切片
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])  #为什么这是个2d的表？因为
print('arr_2d:\n',arr_2d)
print('选取第三行第三列:\n',arr_2d[2,2])
print('选取第一行: \n',arr_2d[1])
print('选取最后一列:\n',arr_2d[:,2]) #行数一定要表示出来，列数可以不表示出来

arr_2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
选取第三行第三列:
 9
选取第一行: 
 [4 5 6]
选取最后一列:
 [3 6 9]


In [5]:
#3.3维数组索引和切片
#那就需要3个索引
arr_3d=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print('arr_3d:\n',arr_3d)
print('axsi 0 :\n',arr_3d[0])
print('axis 0=1,aixs1=0,axis2=2:\n',arr_3d[1][0][2])

arr_3d:
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
axsi 0 :
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


IndexError: index 1 is out of bounds for axis 0 with size 1

In [8]:
#4. 高级索引，这里不是很懂，为什么可以用weekdays 对data进行索引
weekdays = np.array(['Mon','Tue','Wed','Thur','Fri','Sat','Sun'])
data  = np.random.randn(7,4) #一组正态分布的数据
print('weekdays: \n',weekdays)
print('data: \n',data)
#如何选择周三的数据？
#将weekdays中Wed变为True，其余的变成False
#bool 数组
print('weekdays bool array: \n',weekdays=='Wed')
wed_and_sat_bool_arr = (weekdays == 'Wed')|(weekdays =='Sat')  #注意这里的书写方式
print('weekdays cond -& Array:\n',wed_and_sat_bool_arr)
print('Fri-data:\n',data[weekdays=='Fri'])
print('wed & sat days:\n',data[wed_and_sat_bool_arr])


weekdays: 
 ['Mon' 'Tue' 'Wed' 'Thur' 'Fri' 'Sat' 'Sun']
data: 
 [[-0.33785862 -1.16639143  0.48744608  0.72505332]
 [ 0.07742565 -1.12599272 -0.30208909  0.12637509]
 [-1.11756326  0.2466456  -0.96282664  0.73307465]
 [-0.53812225  0.60456081  0.54002429 -1.28253266]
 [ 1.95243869  0.47708912  0.56947595 -0.04612087]
 [-0.52221758  0.18433071 -0.95551546 -0.89675068]
 [ 0.59825884 -0.26788498  1.37133266  0.63665267]]
weekdays bool array: 
 [False False  True False False False False]
weekdays cond -& Array:
 [False False  True False False  True False]
Fri-data:
 [[ 1.95243869  0.47708912  0.56947595 -0.04612087]]
wed & sat days:
 [[-1.11756326  0.2466456  -0.96282664  0.73307465]
 [-0.52221758  0.18433071 -0.95551546 -0.89675068]]


In [10]:
#简单的逻辑计算
weekdays = np.array(['Mon','Tue','Wed','Thur','Fri','Sat','Sun'])
data  = np.random.randn(7,4) #一组正态分布的数据
print('data <0:\n',data[data<0]) #打印出data中小于0的数据
#数据清洗
data_clean = data.copy()  #这里用到copy()是因为后面要修改数据
data_clean[data_clean < 0] =0 #把小于0的部分全部变成0
print('data < 0(=0): \n',data_clean)
#结合bool索引逻辑
data[(weekdays=='Wed')|(weekdays=='Sat')]=10 #把周三和周六的数据变成10
print('Wed & Sat- data(=10):\n',data)

data <0:
 [-0.29675211 -1.34820737 -0.34665514 -0.89683604 -0.58246161 -1.54748304
 -0.37871937 -0.78755504 -1.84100957 -0.54083298 -0.4881139  -2.43907778
 -0.63853571]
data < 0(=0): 
 [[0.33526394 0.73952144 0.         0.30900101]
 [0.         1.05766319 0.         0.74485981]
 [0.         0.63936158 0.         0.0985125 ]
 [1.20493246 0.         0.17790647 0.        ]
 [1.53477156 0.23939207 1.14417984 0.        ]
 [1.18308391 0.82377074 0.         0.        ]
 [0.         1.39120292 0.         0.        ]]
Wed & Sat- data(=10):
 [[ 0.33526394  0.73952144 -0.29675211  0.30900101]
 [-1.34820737  1.05766319 -0.34665514  0.74485981]
 [10.         10.         10.         10.        ]
 [ 1.20493246 -1.54748304  0.17790647 -0.37871937]
 [ 1.53477156  0.23939207  1.14417984 -0.78755504]
 [10.         10.         10.         10.        ]
 [-0.4881139   1.39120292 -2.43907778 -0.63853571]]
