In [ ]:
#首先Numpy和Pandas的区别
#Numpy是一个数据计算库，以ndarray为核心，主要针对矩阵和计算。一般计算用Numpy
#Pandas着重于表格，主要用于数据分析，量化和金融（废话，金融数据大多都是表格类型，而不是矩阵类型），而复杂的表格合并和查询的话用pandas

In [ ]:
#本章内容
#1. ndarray的特性和切片索引
#2. 常用函数
#3. 常用统计函数
#4. 简单集合运算
#5. 随机函数运用

In [6]:
import numpy as np
#array()函数，list→array
np.array([1,2,3])

array([1, 2, 3])

In [5]:
import numpy as np
#tuple→array
np.array((4,5,6))

array([4, 5, 6])

In [7]:
#np.array和np.asarray的区别
arr1=np.array([[1,2,3],[4,5,6]]) #注意有两个中括号
arr2=np.array(arr1)
arr3=np.asanyarray(arr1)
arr1[1] = 0  #这里将第一个列表赋值为0
print('arr1:\n',arr1)
print('arr2:\n',arr2)
print('arr3:\n',arr3)
#可以看出np.array()是不会改变的
#np.asanyarray()是会改变的

arr1:
 [[1 2 3]
 [0 0 0]]
arr2:
 [[1 2 3]
 [4 5 6]]
arr3:
 [[1 2 3]
 [0 0 0]]


In [9]:
#np.arrange()，和list中的range()是一样的
list_range = [x for x in range(1,10) ] #解析列表
arr_range = np.arange(1,10)
print('list : \n',list_range,type(list_range))
print('arr: \n',arr_range,type(arr_range))

list : 
 [1, 2, 3, 4, 5, 6, 7, 8, 9] <class 'list'>
arr: 
 [1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


In [11]:
#np.ones 全部是1的矩阵
arr_ones = np.ones((2,2)) #表示是一个2*2的矩阵
#np.ones_like
arr_ones_likes = np.ones_like(arr1) #这个生成的不是arr1,而是生成的和arr1相同的行数和列数的全1矩阵
print('arr1 : \n', arr1)
print('arr_ones_likes : \n', arr_ones_likes)

arr1 : 
 [[1 2 3]
 [0 0 0]]
arr_ones_likes : 
 [[1 1 1]
 [1 1 1]]


In [ ]:
#np.zeros & np.zeros_like


In [12]:
#np.empty & np.empty_like
#empty列表并不意味着就是没有任何元素的，empty表示的是占据一个内存的位置，如果该位置有元素就会显示出来
arr_empty  = np.empty((2,2))
arr_empty_like = np.empty_like(arr1)
print('arr_empty : \n', arr_empty)
print('arr_empty_like : \n', arr_empty_like)

arr_empty : 
 [[6.91499233e-310 4.63867385e-310]
 [1.58101007e-322 0.00000000e+000]]
arr_empty_like : 
 [[139961002904488  93887806318928               0]
 [              0               0               0]]


In [13]:
#np.eye 对角方阵
arr_eye = np.eye(3) #3*3的对角方阵
print('arr_eye : \n', arr_eye)

arr_eye : 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
